src/accounts/urls.py
from django.urls import path

from src.accounts.views import auth_views, profile_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.Login.as_view(), name='login'),
    path('register/', auth_views.RegisterView.as_view(), name='register'),
    path('logout/', auth_views.Logout.as_view(), name='logout'),
    path(
        'profile/',
        profile_views.SelfProfileView.as_view(),
        name='self-profile'
    ),
    path(
        'profile/update/',
        profile_views.ProfileUpdateView.as_view(),
        name='profile-update'
    ),
    path(
        'profile/<str:username>',
        profile_views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'address/add/',
        profile_views.AddressCreateView.as_view(),
        name='address-create'
    ),
    path(
        'addresses/',
        profile_views.AddressListView.as_view(),
        name='address-list'
    ),
    path(
        'address/<int:pk>/update/',
        profile_views.AddressUpdateView.as_view(),
        name='address-update'
    ),
]

src/root/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.UserHomeView.as_view(), name='home'),
    path('set-language/', views.set_language, name='set_language'),
]

src/shopping/urls.py
from django.urls import path

from .views import cart_views, order_views, payment_views

app_name = 'shopping'

urlpatterns = [
    path('cart/add/', cart_views.AddToCartView.as_view(), name='add_to_cart'),
    path(
        'cart/remove/',
        cart_views.RemoveFromCartView.as_view(),
        name='remove_from_cart'
    ),
    path(
        'cart/delete/',
        cart_views.DeleteFromCartView.as_view(),
        name='delete_from_cart'
    ),
    path('cart/', cart_views.cart_detail, name='cart-detail'),
    path(
        'orders/',
        order_views.OrderHistoryView.as_view(),
        name='order-history'
    ),
    path(
        'order/<int:pk>/',
        order_views.OrderDetailView.as_view(),
        name='order-detail'
    ),
    path('checkout/', order_views.PlaceOrderView.as_view(), name='checkout'),
    path(
        'payment/<int:pk>/',
        payment_views.PaymentView.as_view(),
        name='payment'
    ),
    path(
        'payment/<int:pk>/success/',
        payment_views.PaymentSuccess.as_view(),
        name='payment_success'
    ),
    path(
        'payment/<int:pk>/fail/',
        payment_views.PaymentFail.as_view(),
        name='payment_fail'
    ),
    path(
        'payment/<int:pk>/cancel/',
        payment_views.payment_cancel,
        name='payment_cancel'
    ),
    path('payment/<int:pk>/ipn/', payment_views.ipn, name='ipn'),
]

src/shopping/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

from src.accounts.models import Address, User
from src.books.models import Book
from src.core.models import BaseModel


class OrderStatusChoices(models.TextChoices):
    PENDING = 'PENDING', 'Pending'
    PROCESSING = 'PROCESSING', 'Processing'
    CONFIRMED = 'CONFIRMED', 'Confirmed'
    SHIPPED = 'SHIPPED', 'Shipped'
    DELIVERED = 'DELIVERED', 'Delivered'
    CANCELLED = 'CANCELLED', 'Cancelled'

    def next_state(self):
        if self == OrderStatusChoices.PENDING:
            return OrderStatusChoices.PROCESSING
        if self == OrderStatusChoices.PROCESSING:
            return OrderStatusChoices.CONFIRMED
        if self == OrderStatusChoices.CONFIRMED:
            return OrderStatusChoices.SHIPPED
        if self == OrderStatusChoices.SHIPPED:
            return OrderStatusChoices.DELIVERED
        return self


class Order(BaseModel):
    user = models.ForeignKey(User,
                             on_delete=models.CASCADE,
                             verbose_name=_('user'),
                             related_name='orders',
                             related_query_name='order'
                             )
    address = models.ForeignKey(Address, on_delete=models.CASCADE,
                                verbose_name=_('address'))
    status = models.CharField(
        max_length=20,
        choices=OrderStatusChoices.choices,
        default=OrderStatusChoices.PENDING,
        verbose_name=_('status')
    )
    books = models.ManyToManyField(Book, through='OrderBook',
                                   verbose_name=_('books'))

    class Meta:
        permissions = (
            ('view_own_order', 'Can view own order'),
            ('place_order', 'Can place order'),
        )

    def total_price(self):
        return self.orderbooks.filter(out_of_stock=False).aggregate(
            total_price=models.Sum(models.F('quantity') * models.F('price'))
        )['total_price']

    def get_next_status(self):
        return OrderStatusChoices.next_state(self.status)

    def __str__(self) -> str:
        return f'{self.user.username} -\
            {self.created_at.strftime("%Y-%m-%d %H:%M:%S")}'


class OrderBook(BaseModel):
    order = models.ForeignKey(
        Order,
        on_delete=models.CASCADE,
        related_name='orderbooks',
        related_query_name='orderbook',
        verbose_name=_('order')
    )
    book = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='orderbooks',
        related_query_name='orderbook',
        verbose_name=_('book')
    )
    quantity = models.IntegerField(verbose_name=_('quantity'))
    price = models.DecimalField(max_digits=10, decimal_places=2,
                                verbose_name=_('price'))
    out_of_stock = models.BooleanField(default=False,
                                       verbose_name=_('out_of_stock'))


class PaymentStatusChoices(models.TextChoices):
    PENDING = 'PENDING', 'Pending'
    SUCCESS = 'SUCCESS', 'Success'
    FAILED = 'FAILED', 'Failed'
    CANCELLED = 'CANCELLED', 'Cancelled'


class Transaction(BaseModel):
    order = models.OneToOneField(
        Order,
        on_delete=models.CASCADE,
        related_name='transaction',
        related_query_name='transaction',
    )
    transaction_id = models.CharField(max_length=50, primary_key=True)
    bank_tran_id = models.CharField(max_length=50, null=True, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    store_amount = models.DecimalField(
        max_digits=10, decimal_places=2, null=True, blank=True
    )
    currency = models.CharField(max_length=5)
    status = models.CharField(max_length=10, choices=PaymentStatusChoices)

src/shopping/forms.py
from django import forms

from src.accounts.models import Address
from src.shopping.models import Order


class OrderForm(forms.ModelForm):

    class Meta:
        model = Order
        fields = ['address']
        widgets = {'address': forms.Select()}

    def __init__(self, *args, **kwargs):
        pk = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)

        self.fields['address'].queryset = Address.objects.filter(user_id=pk)

src/shopping/views/cart_views.py
from django.http import JsonResponse
from django.shortcuts import render
from django.views import View

from src.books.models import Book
from src.shopping.utils import load_json_request


class AddToCartView(View):

    def post(self, request):
        data = load_json_request(request)
        book_id = data.get('product_id')

        book = Book.objects.get(pk=book_id)

        if book is None:
            return JsonResponse({'error': 'Book not found.'}, status=404)

        if book.quantity < 1:
            return JsonResponse({'error': 'Sorry, this book is out of stock.'},
                                status=400)

        if request.session.get('cart') is None:
            request.session['cart'] = {}

        cart = request.session['cart']

        cart[str(book.pk)] = cart.get(str(book.pk), 0) + 1
        request.session.modified = True

        return JsonResponse({
            'message': 'Book added to cart successfully.',
            'cart_count': cart[str(book.pk)]
        },
                            status=200)


class RemoveFromCartView(View):

    def post(self, request):
        data = load_json_request(request)
        book_id = data.get('product_id')

        book = Book.objects.get(pk=book_id)

        if book is None:
            return JsonResponse({'error': 'Book not found.'}, status=404)

        if request.session.get('cart') is None:
            return JsonResponse({'error': 'Cart is empty.'}, status=400)

        cart = request.session['cart']

        if str(book.pk) not in cart:
            return JsonResponse({'error': 'Book not in cart.'}, status=400)

        cart[str(book.pk)] -= 1
        if cart[str(book.pk)] == 0:
            del cart[str(book.pk)]
        request.session.modified = True

        return JsonResponse({
            'message': 'Book removed from cart successfully.',
            'cart_count': cart.get(str(book.pk), 0)
        },
                            status=200)


class DeleteFromCartView(View):

    def post(self, request):
        data = load_json_request(request)
        book_id = data.get('product_id')

        book = Book.objects.get(pk=book_id)

        if book is None:
            return JsonResponse({'error': 'Book not found.'}, status=404)

        if request.session.get('cart') is None:
            return JsonResponse({'error': 'Cart is empty.'}, status=400)

        cart = request.session['cart']

        if str(book.pk) not in cart:
            return JsonResponse({'error': 'Book not in cart.'}, status=400)

        del cart[str(book.pk)]
        request.session.modified = True

        return JsonResponse({
            'message': 'Book removed from cart successfully.',
            'cart_count': 0
        },
                            status=200)


def cart_detail(request):
    cart = request.session.get('cart', {})
    books = Book.objects.filter(id__in=cart.keys())

    book_list = []
    total = 0
    for book in books:
        book_list.append({
            'id': book.pk,
            'title': str(book),
            'price': book.price,
            'quantity': cart[str(book.pk)],
            'total_price': book.price * cart[str(book.pk)],
            'is_in_stock': book.quantity >= cart[str(book.pk)]
        })
        total += book.price * cart[str(book.pk)]

    return render(
        request, 'shopping/cart-detail.html', {
            'books': book_list,
            'total': total
        }
    )

src/shopping/views/order_views.py
from django.contrib import messages
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.db import models
from django.db.utils import IntegrityError
from django.shortcuts import redirect
from django.urls import reverse
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from src.books.models import Book
from src.core.mixins import OwnerRequiredMixin
from src.shopping.forms import OrderForm
from src.shopping.models import Order, OrderBook


class OrderHistoryView(PermissionRequiredMixin, ListView):
    model = Order
    template_name = 'shopping/order-history.html'
    context_object_name = 'orders'
    paginate_by = 10
    permission_required = ('shopping.view_own_order',)

    def get_queryset(self):
        return Order.objects.filter(user=self.request.user
                                    ).order_by('-created_at')


class OrderDetailView(OwnerRequiredMixin, DetailView):
    model = Order
    template_name = 'shopping/order-detail.html'
    context_object_name = 'order'
    permission_required = ('shopping.view_own_order',)

    def is_owner(self, request):
        return self.get_object().user == request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['books'] = self.object.orderbooks.annotate(
            title=models.F('book__title')
        ).annotate(
            total_price=models.F('book__price') * models.F('quantity')
        ).values('title', 'quantity', 'price', 'total_price', 'out_of_stock')
        return context


class PlaceOrderView(PermissionRequiredMixin, CreateView):
    model = Order
    template_name = 'shopping/checkout.html'
    form_class = OrderForm
    permission_required = ('shopping.place_order',)

    def get_success_url(self):
        pk = self.object.pk
        return reverse('shopping:payment', kwargs={'pk': pk})

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['user_id'] = self.request.user.pk
        return kwargs

    def get(self, request, *args, **kwargs):
        if not self.request.session.get('cart') or len(
            self.request.session['cart']
        ) == 0:
            messages.error(self.request, 'Your cart is empty')
            return redirect('shopping:cart-detail')
        return super().get(request, *args, **kwargs)

    def form_valid(self, form):
        cart = self.request.session.get('cart', {})
        if len(cart) == 0:
            messages.error(self.request, 'Your cart is empty')
            return redirect('shopping:cart-detail')

        form.instance.user = self.request.user

        self.object = form.save()

        for book_id, quantity in cart.items():
            book = Book.objects.get(id=book_id)
            order_item = OrderBook.objects.create(
                order=self.object,
                book=book,
                price=book.price,
                quantity=quantity
            )
            try:
                book.quantity -= quantity
                book.save()
            except IntegrityError as e:
                print(e)
                order_item.out_of_stock = True
                continue

        self.request.session['cart'] = {}
        return redirect(self.get_success_url())

src/shopping/views/payment_views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse
from django.utils.decorators import method_decorator
from django.views import View
from django.views.decorators.csrf import csrf_exempt

from src.shopping.models import (
    Order, OrderStatusChoices, PaymentStatusChoices, Transaction
)
from src.shopping.tasks import send_confirmation_email
from src.shopping.utils import (
    init_getway, validate_failure_response, verify_payment
)


class PaymentView(LoginRequiredMixin, View):

    def get(self, request, pk):
        order = Order.objects.get(pk=pk)
        if order.status != OrderStatusChoices.PENDING:
            return redirect('shopping:cart-detail')
        books = order.books.all()
        amount = order.total_price()
        customer = request.user
        address = order.address
        urls = {
            'success': reverse('shopping:payment_success', kwargs={'pk': pk}),
            'fail': reverse('shopping:payment_fail', kwargs={'pk': pk}),
            'cancel': reverse('shopping:payment_cancel', kwargs={'pk': pk}),
            'ipn': reverse('shopping:ipn', kwargs={'pk': pk})
        }
        tran_id, response = init_getway(
            request, amount, customer, address, books, urls
        )

        if response['status'] == 'SUCCESS':
            Transaction.objects.create(
                order=order,
                transaction_id=tran_id,
                amount=amount,
                currency='BDT',
                status='PENDING'
            )
            return redirect(response['GatewayPageURL'])

        return redirect('shopping:payment_fail', pk=pk)


@method_decorator(csrf_exempt, name='dispatch')
class PaymentSuccess(View):

    def post(self, request, pk):
        response = verify_payment(request.POST)
        if response and response['status'] == 'VALID':
            order = get_object_or_404(Order, pk=pk)
            order.status = OrderStatusChoices.PROCESSING
            order.save()
            transaction = Transaction.objects.get(
                transaction_id=response['tran_id']
            )
            transaction.bank_tran_id = response['bank_tran_id']
            transaction.store_amount = response['store_amount']
            transaction.status = PaymentStatusChoices.SUCCESS
            transaction.save()
            messages.success(request, 'Payment Successful')
            send_confirmation_email.delay(order.pk)
        return redirect('shopping:cart-detail')


@method_decorator(csrf_exempt, name='dispatch')
class PaymentFail(View):

    def post(self, request, pk):
        if validate_failure_response(request.POST):
            order = get_object_or_404(Order, pk=pk)
            order.status = OrderStatusChoices.CANCELLED
            order.save()
            cart = {}
            for order_item in order.orderbooks.all():
                order_item.book.quantity += order_item.quantity
                order_item.book.save()

                cart[order_item.book.pk] = order_item.quantity

            request.session['cart'] = cart

            transaction = Transaction.objects.get(
                transaction_id=request.POST['tran_id']
            )
            transaction.status = PaymentStatusChoices.FAILED
            transaction.bank_tran_id = request.POST['bank_tran_id']
            transaction.save()
            messages.error(request, 'Payment Failed')

            return redirect('shopping:cart-detail')


@csrf_exempt
def payment_cancel(request, pk):
    return redirect('shopping:payment_fail', pk=pk)


@csrf_exempt
def ipn(request, pk):
    response = verify_payment(request.POST)
    if response:
        print(response)
    return redirect('shopping:checkout')

src/shopping/templates/shopping/cart-detail.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block extra_scripts %}
<script src="{% static 'shopping/script.js' %}" defer></script>
{% endblock extra_scripts %}

{% block title %}{% trans "Cart" %}{% endblock %}

{% block content %}
<div class="flex justify-center items-start m-10">
  <div class="text-center">
    <h1 class="text-3xl font-bold mb-4">{% trans "Cart" %}</h1>
    <table class="w-full">
      <thead>
        <tr class="bg-cyan-100">
          <th class="text-left px-2 py-1">{% trans "Books" %}</th>
          <th class="text-left px-2 py-1">{% trans "Quantity" %}</th>
          <th class="text-left px-2 py-1">{% trans "Price" %}</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td class="text-left px-2 py-1">{{ book.title }}</td>
          <td class="text-center px-2 py-1">
            <button class="text-indigo-600 hover:text-indigo-800" onclick="remove_from_cart({{ book.id }}, `{% url 'shopping:remove_from_cart' %}`, 'cart')"><i class="fas fa-minus-circle"></i></button>
            <span id="cart_count{{ book.id }}">{{ book.quantity }}</span>
            <button class="text-indigo-600 hover:text-indigo-800" onclick="add_to_cart({{ book.id }}, `{% url 'shopping:add_to_cart' %}`, 'cart')"><i class="fas fa-plus-circle"></i></button>
          </td>
          <td class="px-2 py-1">{{ book.total_price }}</td>
          <td class="px-2 py-1"><button class="text-red-600 hover:text-red-800" onclick="delete_from_cart({{ book.id }}, `{% url 'shopping:delete_from_cart' %}`)"><i class="fas fa-times-circle"></i></button></td>
        </tr>
        {% endfor %}
        <tr class="bg-cyan-100">
          <td class="text-left px-2 py-1"></td>
          <td class="text-center px-2 py-1 font-bold">{% trans "Total" %}</td>
          <td class="px-2 py-1">{{ total }}</td>
          <td></td>
        </tr>
      </tbody>
    </table>
    <div class="text-center mt-4">
      <button class="bg-blue-500 px-4 py-2 text-white" onclick="location.href='{% url 'shopping:checkout' %}'">{% trans "Checkout" %}</button>
    </div>
  </div>
</div>
{% endblock %}

src/shopping/templates/shopping/checkout.html
{% extends 'base.html' %}

{% load i18n %}

{% block title %}{% trans "Checkout" %}{% endblock %}

{% block content %}
  <div class="bg-gray-100 rounded-lg shadow-md overflow-hidden m-10 p-4">
    <h2 class="text-3xl font-semibold mb-4">{% trans "Checkout" %}</h2>
    Add your address <a class="text-blue-500" href="{% url 'accounts:address-create' %}?next={% url "shopping:checkout" %}">here</a> if you haven't already.
    {% include "_form.html" with submit_text="Place Order" %}
  </div>
{% endblock %}

src/shopping/templates/shopping/order-detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "OrderDetail" %}{% endblock %}

{% block content %}
<div class="flex justify-center items-start m-10">
  <div class="text-center">
    <h1 class="text-3xl font-bold mb-4 text-indigo-600">{% trans "OrderDetail" %}</h1>
    <h2 class="text-lg mb-2">{% trans "Date" %}: {{ order.created_at }}</h2>
    <h2 class="text-lg mb-4">{% trans "Order Status" %}: {{ order.get_status_display }}</h2>
    <table class="w-full mt-10">
      <thead>
        <tr class="bg-cyan-100">
          <th class="text-left px-2 py-1">{% trans "Books" %}</th>
          <th class="text-left px-2 py-1">{% trans "Quantity" %}</th>
          <th class="text-left px-2 py-1">{% trans "Price" %}</th>
        </tr>
      </thead>
      <tbody>
        {% for book in books %}
        <tr>
          <td class="text-left px-2 py-1">{{ book.title }}</td>
          <td class="text-center px-2 py-1">{{ book.quantity }}</td>
          <td class="px-2 py-1">{{ book.total_price }}</td>
        </tr>
        {% endfor %}
        <tr class="bg-cyan-100">
          <td class="text-left px-2 py-1"></td>
          <td class="text-center px-2 py-1 font-bold">{% trans "Total" %}</td>
          <td class="px-2 py-1">{{ order.total_price }}</td>
        </tr>
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

src/shopping/templates/shopping/order-history.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "OrderHistory" %}{% endblock %}

{% block content %}
<div class="container mx-auto p-4">
    <div class="flex gap-4 mb-2">
        <h2 class="text-3xl font-semibold mb-4">{% trans "OrderHistory" %}</h2>
    </div>
    <div class="grid grid-cols-2 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {% for order in page_obj %}
        <div class="bg-gray-100 rounded-lg shadow-md overflow-hidden">
            <div class="bg-cyan-200 px-4 py-2 flex justify-between items-center gap-2">
                <h3 class="text-xl font-semibold text-gray-800">{{ order.user.first_name }}</h3>
                <a href="{% url 'shopping:order-detail' order.id %}"
                    class="text-blue-600 hover:text-blue-900 font-semibold">{% trans "View" %}</a>
            </div>
            <div class="p-4">
                <p class="text-gray-600 mb-2"><strong>{% trans "Date" %}:</strong> {{ order.created_at }}</p>
                <p class="text-gray-600 mb-2"><strong>{% trans "Address" %}:</strong> {{ order.address }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="mt-4">
      {% if page_obj.has_previous %}
        <a href="?page=1" class="border border-gray-300 px-3 py-1 mr-2 rounded-md bg-white text-gray-700 hover:bg-gray-50">&laquo; {% trans "First" %}</a>
        <a href="?page={{ page_obj.previous_page_number }}" class="border border-gray-300 px-3 py-1 mr-2 rounded-md bg-white text-gray-700 hover:bg-gray-50">&lsaquo; {% trans "Previous" %}</a>
      {% endif %}
        <span class="text-gray-700">{{ page_obj.number }} / {{ page_obj.paginator.num_pages }}</span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}" class="border border-gray-300 px-3 py-1 ml-2 rounded-md bg-white text-gray-700 hover:bg-gray-50">{% trans "Next" %} &rsaquo;</a>
        <a href="?page={{ page_obj.paginator.num_pages }}" class="border border-gray-300 px-3 py-1 ml-2 rounded-md bg-white text-gray-700 hover:bg-gray-50">{% trans "Last" %} &raquo;</a>
      {% endif %}
    </div>
</div>
{% endblock %}