src/accounts/urls.py
from django.urls import path

from src.accounts.views import auth_views, profile_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.Login.as_view(), name='login'),
    path('register/', auth_views.RegisterView.as_view(), name='register'),
    path('logout/', auth_views.Logout.as_view(), name='logout'),
    path(
        'profile/',
        profile_views.SelfProfileView.as_view(),
        name='self-profile'
    ),
    path(
        'profile/update/',
        profile_views.ProfileUpdateView.as_view(),
        name='profile-update'
    ),
    path(
        'profile/<str:username>',
        profile_views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'address/add/',
        profile_views.AddressCreateView.as_view(),
        name='address-create'
    ),
    path(
        'addresses/',
        profile_views.AddressListView.as_view(),
        name='address-list'
    ),
    path(
        'address/<int:pk>/update/',
        profile_views.AddressUpdateView.as_view(),
        name='address-update'
    ),
]

src/book_review/urls.py
from django.urls import path

from .views import (
    BookReviewListView, ReviewCreateView, ReviewUpdateView, UserReviewListView
)

app_name = 'review'

urlpatterns = [
    path('<int:pk>/', BookReviewListView.as_view(), name='reviews'),
    path(
        'user/<str:username>/',
        UserReviewListView.as_view(),
        name='user-reviews'
    ),
    path('<int:pk>/update/', ReviewUpdateView.as_view(), name='update-review'),
    path('<int:pk>/create/', ReviewCreateView.as_view(), name='create-review'),
    # path('update_review/',ReviewUpdateView.as_view(), name="update_view")
]

src/root/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.UserHomeView.as_view(), name='home'),
    path('set-language/', views.set_language, name='set_language'),
]

src/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import gettext_lazy as _
from django_countries.fields import CountryField

from src.accounts.managers import CustomerManager, StaffManager, UserManager
from src.core.models import BaseModel


class User(AbstractUser):
    phone = models.CharField(max_length=20,
                             verbose_name=_('phone'))
    email = models.EmailField(_('email address'), unique=True)
    objects = UserManager()

    class Meta:
        permissions = (
            ('view_profile', 'Can view profile'),
            ('change_own_profile', 'Can change own profile'),
        )


class Customer(User):
    objects = CustomerManager()

    class Meta:
        proxy = True
        verbose_name = _('customer')
        verbose_name_plural = _('customers')


class Staff(User):
    objects = StaffManager()

    class Meta:
        proxy = True
        verbose_name = _('staff')
        verbose_name_plural = _('staffs')


class Address(BaseModel):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE,
        related_name='addresses',
        related_query_name='address',
        verbose_name=_('user')
    )

    house = models.CharField(verbose_name=_('house'))
    street = models.CharField(verbose_name=_('street'))
    city = models.CharField(verbose_name=_('city'))
    state = models.CharField(blank=True, null=True, verbose_name=_('state'))
    country = models.CharField(
        max_length=3,
        choices=CountryField().countries,
        verbose_name=_('country')
    )
    post_code = models.CharField(verbose_name=_('post_code'))

    class Meta:
        verbose_name = _('address')
        verbose_name_plural = _('addresses')
        permissions = (
            ('add_own_address', 'Can add own address'),
            ('view_own_address', 'Can view own address'),
            ('change_own_address', 'Can change own address'),
        )

    def __str__(self):
        return f'{self.house}, {self.street}, {self.get_country_display()}'

src/accounts/forms.py
# forms.py

from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm

from .models import User


# FIXME: need to add phone field and validate that it's within 20 characters
class RegisterForm(UserCreationForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Confirm Password', widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'phone', 'username']

    def clean_password2(self):
        password1 = self.cleaned_data.get('password1')
        password2 = self.cleaned_data.get('password2')
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError('Passwords do not match')
        return password2


class CustomAuthenticationForm(AuthenticationForm):

    class Meta:
        model = User
        fields = ['username', 'password']

src/accounts/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import reverse_lazy
from django.views.generic import CreateView

from .forms import CustomAuthenticationForm, RegisterForm


class Login(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        # Get the 'next' parameter from the GET request
        next_url = self.request.GET.get('next')
        # If 'next' parameter exists, redirect to it, otherwise use LOGIN_REDIRECT_URL # noqa: E501
        if next_url:
            return next_url
        else:
            return super().get_success_url()


class RegisterView(CreateView):
    form_class = RegisterForm
    template_name = 'register.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        # Hash the password before saving
        password = form.cleaned_data['password1']
        form.instance.set_password(password)

        form.save()
        # get the username and password
        username = self.request.POST['username']
        password = self.request.POST['password1']
        # authenticate user then login
        user = authenticate(username=username, password=password)
        login(self.request, user)

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_initial_data'] = self.request.POST
        return context


class Logout(LogoutView):
    next_page = reverse_lazy('login')

src/accounts/views/auth_views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import CreateView

from src.accounts.forms import CustomAuthenticationForm, RegisterForm
from src.accounts.mixins import UnauthenticatedRequiredMixin


class Login(LoginView):
    form_class = CustomAuthenticationForm
    template_name = 'accounts/login.html'
    redirect_authenticated_user = True

    def get_success_url(self):
        # Get the 'next' parameter from the GET request
        next_url = self.request.GET.get('next')
        # If 'next' parameter exists, redirect to it, otherwise use LOGIN_REDIRECT_URL # noqa: E501
        if next_url:
            return next_url
        else:
            return super().get_success_url()


class RegisterView(UnauthenticatedRequiredMixin, CreateView):
    form_class = RegisterForm
    template_name = 'accounts/register.html'
    success_url = reverse_lazy('home')

    def form_valid(self, form):
        password = form.cleaned_data['password1']
        form.instance.set_password(password)

        form.save()
        username = self.request.POST['username']
        password = self.request.POST['password1']

        group = Group.objects.get(name='base_user')
        form.instance.groups.add(group)

        user = authenticate(username=username, password=password)
        login(self.request, user)

        return redirect(self.success_url)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form_initial_data'] = self.request.POST
        return context


class Logout(LogoutView):
    next_page = reverse_lazy('accounts:login')

src/accounts/views/profile_views.py
from django.contrib.auth.mixins import (
    LoginRequiredMixin, PermissionRequiredMixin
)
from django.shortcuts import get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from src.accounts.models import Address, User
from src.core.mixins import OwnerRequiredMixin


class SelfProfileView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/self-profile.html'
    context_object_name = 'user'

    def get_object(self):
        return get_object_or_404(User, username=self.request.user.username)


class ProfileView(PermissionRequiredMixin, DetailView):
    model = User
    template_name = 'accounts/profile.html'
    context_object_name = 'user'
    permission_required = ('accounts.view_profile',)

    def get_object(self):
        return get_object_or_404(User, username=self.kwargs['username'])

    def get(self, request, *args, **kwargs):
        if request.user.username == self.get_object().username:
            return redirect('accounts:self-profile')
        return super().get(request, *args, **kwargs)


class ProfileUpdateView(OwnerRequiredMixin, UpdateView):
    model = User
    fields = ['first_name', 'last_name', 'email', 'phone']
    template_name = 'accounts/profile-update.html'
    success_url = reverse_lazy('accounts:self-profile')
    permission_required = ('accounts.change_own_profile',)

    def is_owner(self, request):
        return self.request.user.username == self.get_object().username

    def get_object(self):
        return self.request.user


class AddressListView(PermissionRequiredMixin, ListView):
    model = User
    template_name = 'accounts/address-list.html'
    context_object_name = 'addresses'
    permission_required = ('accounts.view_own_address',)

    def get_queryset(self):
        return self.request.user.addresses.all()


class AddressCreateView(PermissionRequiredMixin, CreateView):
    model = Address
    fields = ['house', 'street', 'city', 'state', 'post_code', 'country']
    template_name = 'accounts/address-create.html'
    success_url = reverse_lazy('accounts:address-list')
    permission_required = ('accounts.add_own_address',)

    def get_success_url(self):
        next_url = self.request.GET.get('next')
        if next_url:
            return next_url
        return super().get_success_url()

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class AddressUpdateView(OwnerRequiredMixin, UpdateView):
    model = Address
    template_name = 'accounts/address-update.html'
    fields = ['house', 'street', 'city', 'state', 'post_code', 'country']
    success_url = reverse_lazy('accounts:address-list')
    permission_required = ('accounts.change_own_address',)

    def is_owner(self, request):
        return self.request.user == self.get_object().user

    def get_object(self):
        return self.model.objects.get(pk=self.kwargs['pk'])

src/accounts/templates/accounts/address-create.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "AddAddress" %}{% endblock %}

{% block content %}
  {% include "form.html" with form_title=_("AddAddress") submit_text=_("AddAddress") %}
{% endblock %}

src/accounts/templates/accounts/address-list.html
{% extends "base.html" %}

{% load i18n %}

{% block title %}{% trans "Addresses" %}{% endblock %}

{% block content %}
<div class="container mx-auto p-4">
    <div class="flex flex-col gap-4 mb-2">
        <h2 class="text-3xl font-semibold mb-4">{% trans "Addresses" %}</h2>
        <div class="mb-4">
          <a href="{% url 'accounts:address-create' %}"
            class="bg-cyan-500 text-white px-4 py-2 rounded-lg hover:bg-cyan-600 transition-colors">{% trans "AddAddress" %}</a>
        </div>
    </div>
    <div class="grid grid-cols-3 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-4">
        {% for address in addresses %}
        <div class="bg-gray-100 rounded-lg shadow-md overflow-hidden">
            <div class="bg-cyan-200 px-4 py-2 flex justify-between items-center gap-2">
                <a href="{% url 'accounts:address-update' address.id %}"
                    class="text-blue-600 hover:text-blue-900 font-semibold">{% trans "UpdateAddress" %}</a>
            </div>
            <div class="p-4">
                <p class="text-gray-600 mb-2">{{ address }}</p>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/address-update.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "UpdateAddress" %}{% endblock title %}


{% block content %}
  {% include "form.html" with form_title=_("UpdateAddress") submit_text=_("UpdateAddress")%}
{% endblock content %}

src/accounts/templates/accounts/login.html
{% extends '_base.html' %}
{% load i18n %}

{% block title %}Login{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <div>
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                {% trans "SignInToYourAccount" %}
            </h2>
        </div>
        <form class="mt-8 space-y-6" method="POST" action="{% url 'accounts:login' %}?next={{next|urlencode}}">
            {% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
                <div>
                    <label for="username" class="sr-only">{% trans "Username" %}</label>
                    <input id="username" name="username" type="text" autocomplete="username" required
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Username">
                    {% if form.errors.username %}
                    <p class="text-red-500 text-xs italic">{{ form.errors.username }}</p>
                    {% endif %}
                </div>
                <div>
                    <label for="password" class="sr-only">{% trans "Password" %}</label>
                    <input id="password" name="password" type="password" autocomplete="current-password" required
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Password">
                    {% if form.errors.password %}
                    <p class="text-red-500 text-xs italic">{{ form.errors.password }}</p>
                    {% endif %}
                </div>
            </div>
            <div>
                <button type="submit"
                    class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    {% trans "LogIn" %}
                </button>
                {% if form.non_field_errors %}
                    <p class="text-red-500 text-xs italic">
                        {% for error in form.non_field_errors %}
                            {{ error }}
                            <br>
                        {% endfor %}
                    </p>
                {% endif %}
            </div>
        </form>

        <div class="w-full text-center">
            <a href="{% url 'accounts:register' %}" class="text-sm text-blue-700">{% trans "RegisterPromt" %}</a>
        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/profile-update.html
{% extends "base.html" %}
{% load i18n %}
{% block title %}{% trans "UpdateProfile" %}{% endblock title %}

{% block content %}
  {% include "form.html" with form_title=_("UpdateProfile") submit_text=_("UpdateProfile") %}
{% endblock content %}

src/accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}
    {{ user.first_name }}'s Profile
{% endblock %}

{% block content %}
  <div class="flex justify-center items-center">
    <div class="max-w-screen-xl rounded overflow-hidden shadow-lg md:mt-20">
        <div class="px-6 py-4">
          <img class="w-full" src="https://via.placeholder.com/150" alt="Profile Picture">
        </div>
        <div class="px-6 py-4">
            <div class="font-bold text-4xl mb-2">{{ user.first_name }} {{ user.last_name }}</div>
            <p class="text-gray-700 text-xl">
              <strong>{% trans "Username" %}:</strong> {{ user.username }}<br>
              <strong>{% trans "email address" %}:</strong> {{ user.email }}<br>
              <strong>{% trans "Phone" %}:</strong> {{ user.phone }}
            </p>
            <div class="mt-4">
              {% block profile_btns %}{% endblock profile_btns %}  
              <a href="{% url "review:user-reviews" username=request.user.username %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2">
                  {% trans "Reviews" %}
              </a>
            </div>
        </div>
    </div>
  </div>
{% endblock %}

src/accounts/templates/accounts/register.html
{% extends '_base.html' %}
{% load i18n %}

{% block title %}Register{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <div>
            <h2 class="mt-6 text-center text-3xl font-extrabold text-gray-900">
                {% trans "CreateYourAccount" %}
            </h2>
        </div>
        <form class="mt-8 space-y-6" method="POST">
            {% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
                <div>
                    <label for="first_name" class="sr-only">{% trans "FirstName" %}</label>
                    <input id="first_name" name="first_name" type="text" required
                        value="{{ form_initial_data.first_name }}"
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="First Name">
                    <span class="text-red-500 text-xs italic">{{ form.errors.first_name }}</span>
                </div>
                <div>
                    <label for="last_name" class="sr-only">{% trans "LastName" %}</label>
                    <input id="last_name" name="last_name" type="text" required
                        value="{{ form_initial_data.last_name }}"
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Last Name">
                    <span class="text-red-500 text-xs italic">{{ form.errors.last_name }}</span>
                </div>
                <div>
                    <label for="email" class="sr-only">{% trans "Email" %}</label>
                    <input id="email" name="email" type="email" required
                        value="{{ form_initial_data.email }}"
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Email">
                    <span class="text-red-500 text-xs italic">{{ form.errors.email }}</span>
                </div>
                <div>
                    <label for="email" class="sr-only">{% trans "Username" %}</label>
                    <input id="username" name="username" type="text" required
                        value="{{ form_initial_data.username }}"
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Username">
                    <span class="text-red-500 text-xs italic">{{ form.errors.username }}</span>
                </div>
                <div>
                    <label for="phone" class="sr-only">{% trans "Phone" %}</label>
                    <input id="phone" name="phone" type="text" required
                        value="{{ form_initial_data.phone }}"
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Phone">
                    <span class="text-red-500 text-xs italic">{{ form.errors.phone }}</span>
                </div>
                <div>
                    <label for="password1" class="sr-only">{% trans "Password" %}</label>
                    <input id="password1" name="password1" type="password" required
                        value="{{ form_initial_data.password1 }}"
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Password">
                    <span class="text-red-500 text-xs italic">{{ form.errors.password1 }}</span>
                </div>
                <div>
                    <label for="password2" class="sr-only">{% trans "ConfirmPassword" %}</label>
                    <input id="password2" name="password2" type="password" required
                        value="{{ form_initial_data.password2 }}"
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Confirm Password">
                    <span class="text-red-500 text-xs italic">{{ form.errors.password2 }}</span>
                </div>
            </div>
            <div>
                <button type="submit"
                    class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    {% trans "Register" %}
                </button>
            </div>
        </form>
        <div class="w-full text-center">
            <a href="{% url 'accounts:login' %}" class="text-sm text-blue-700">{% trans "LoginPromt" %}</a>
        </div>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/self-profile.html
{% extends "accounts/profile.html" %}
{% load i18n %}
{% block profile_btns %}
  <a href="{% url "accounts:profile-update" %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
    {% trans "UpdateProfile" %}
  </a>
  <a href="{% url "accounts:address-list" %}" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded ml-2">
    {% trans "Addresses" %}
  </a>
{% endblock profile_btns %}