src/book_review/urls.py
from django.urls import path

from .views import (
    BookReviewListView, ReviewCreateView, ReviewUpdateView, UserReviewListView
)

app_name = 'review'

urlpatterns = [
    path('<int:pk>/', BookReviewListView.as_view(), name='reviews'),
    path(
        'user/<str:username>/',
        UserReviewListView.as_view(),
        name='user-reviews'
    ),
    path('<int:pk>/update/', ReviewUpdateView.as_view(), name='update-review'),
    path('<int:pk>/create/', ReviewCreateView.as_view(), name='create-review'),
    # path('update_review/',ReviewUpdateView.as_view(), name="update_view")
]

src/root/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.UserHomeView.as_view(), name='home'),
    path('set-language/', views.set_language, name='set_language'),
]

src/book_review/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils.translation import gettext_lazy as _

from src.accounts.models import User
from src.books.models import Book
from src.core.models import BaseModel


class Review(BaseModel):
    ratings = models.IntegerField(
        validators=[MaxValueValidator(5),
                    MinValueValidator(1)],
        verbose_name=_('ratings')
    )
    comments = models.TextField(verbose_name=_('comments'))
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='reviews',
        related_query_name='review',
        verbose_name=_('user')
    )
    books = models.ForeignKey(
        Book,
        on_delete=models.CASCADE,
        related_name='reviews',
        related_query_name='review',
        verbose_name=_('book')
    )

    class Meta:
        permissions = (
            ('add_own_review', 'Can add own review'),
            ('change_own_review', 'Can change own review'),
            ('view_own_review', 'Can view own review'),
        )

src/book_review/forms.py
from django import forms

from .models import Review


class ReviewForm(forms.ModelForm):

    class Meta:
        model = Review
        fields = ['ratings', 'comments']

src/book_review/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic.edit import CreateView, UpdateView
from django.views.generic.list import ListView

from .forms import ReviewForm
from .models import Book, Review

app_name = 'accounts'


class BookReviewListView(ListView):
    model = Review
    context_object_name = 'reviews'
    template_name = 'review_list_book.html'

    def get_queryset(self):
        pk = self.kwargs['pk']
        return Review.objects.filter(books__id=pk)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        pk = self.kwargs['pk']
        book = get_object_or_404(Book, pk=pk)
        context['book'] = book
        return context


class ReviewCreateView(PermissionRequiredMixin, CreateView):
    model = Review
    form_class = ReviewForm
    template_name = 'create_review.html'
    success_url = reverse_lazy('book-list')
    permission_required = ('book_review.add_own_review',)

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.instance.books = Book.objects.get(pk=self.kwargs.get('pk'))
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['book'] = Book.objects.get(pk=self.kwargs.get('pk'))
        return context


class UserReviewListView(PermissionRequiredMixin, ListView):
    model = Review
    context_object_name = 'reviews'
    template_name = 'review_list_user.html'
    permission_required = ('book_review.view_own_review',)

    def get_queryset(self):
        return Review.objects.filter(user=self.request.user)


class ReviewUpdateView(PermissionRequiredMixin, UpdateView):
    model = Review
    form_class = ReviewForm
    template_name = 'update_review.html'
    permission_required = ('book_review.change_own_review',)

    def get_success_url(self):
        return reverse_lazy(
            'review:user-reviews',
            kwargs={'username': self.request.user.username}
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['review'] = Review.objects.get(pk=self.kwargs.get('pk'))
        context['url'] = self.request.META.get('HTTP_REFERER')
        return context

    def is_owner(self, request):
        return self.get_object().user == request.user

src/book_review/templates/create_review.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Add review{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <form class="mt-8 space-y-6" method="POST" action="">

            {{book}}
            {% csrf_token %}
            <div class="rounded-md shadow-sm -space-y-px">
                <div>
                    <label for="ratings" class="sr-only">Ratings</label>
                    <input id="ratings" name="ratings" type="text" autocomplete="ratings" required
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="Ratings">
                    {% if form.errors.ratings %}
                    <p class="text-red-500 text-xs italic">{{ form.errors.ratings }}</p>
                    {% endif %}
                </div>
                <div>
                    <label for="comments" class="sr-only">Comments</label>
                    <textarea id="comments" name="comments" type="text-area"  autocomplete="comments" required
                        class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm"
                        placeholder="comments"></textarea>
                    {% if form.errors.ratings %}   
                    <p class="text-red-500 text-xs italic">{{ form.errors.comments }}</p>
                    {% endif %}
                </div>
            </div>
            <div>
                <button type="submit"
                    class="group relative w-full flex justify-center py-2 font-bold px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    {% trans 'Update'%}
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}

src/book_review/templates/review_list_book.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div class="min-h-screen flex justify-center items-center bg-gray-100">
  <div class="flex flex-col items-center">
    <div class="bg-gray-100 rounded-lg shadow-md overflow-hidden">
      <div class="bg-cyan-200 px-4 py-2 flex justify-between items-center gap-2">
            <h2 class="text-2xl font-semibold text-gray-800">{{ book.title}}</h2>
        </div>
        <div class="bg-cyan-200 px-4 py-2 flex justify-between items-center gap-2">
          <h3 class="text-2xl font-semibold text-gray-800">{% trans 'Reviews' %}</h3>
      </div>
      <div class="p-4">
        <div class="mb-4">
          {% for r in reviews %}          
            <div class="border border-gray-200 rounded-md p-2 mb-2">
              <p class="text-lg font-semibold text-lime-500">{{ r.user.username }}</p>
              <div class="mb-1">
                {% for i in r.range %}
                  &starf;
                {% endfor %}
              </div>
              <p class="text-gray-700">{{ r.comments }}</p>
            </div>
          {% endfor %}
        </div>
        <a href="{% url 'review:create-review' pk=book.id %}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md text-sm">{% trans 'AddAReview'%}</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/book_review/templates/review_list_user.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
<div class="min-h-screen flex justify-center items-center bg-gray-100">
  <div class="flex flex-col items-center">
    <div class="bg-gray-100 rounded-lg shadow-md overflow-hidden">
      <div class="bg-cyan-200 px-4 py-2 flex justify-between items-center gap-2">
            <h2 class="text-2xl font-semibold text-gray-800">{{ request.user.first_name }} {{ request.user.last_name  }}</h2>
        </div>
        <div class="bg-cyan-200 px-4 py-2 flex justify-between items-center gap-2">
          <h3 class="text-2xl font-semibold text-gray-800">{% trans 'Reviews' %}</h3>
      </div>
      <div class="p-4">
        <div class="mb-4">
          {% for r in reviews %}          
            <div class="border border-gray-200 rounded-md p-2 mb-2">
              <p class="text-lg font-semibold text-lime-500">{{ r.books.title }}</p>
              <div class="mb-1">
                {% for i in r.range %}
                  &starf;
                {% endfor %}
              </div>
              <p class="text-gray-700">{{ r.comments }}</p>
              <div>
                <a href="{% url 'review:update-review' pk=r.id %}" class="inline-block bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-md text-sm">{% trans 'Update'%}</a>
              </div>
            </div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

src/book_review/templates/update_review.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Update Review{% endblock %}

{% block content %}
<div class="min-h-screen flex items-center justify-center bg-gray-50 py-12 px-4 sm:px-6 lg:px-8">
    <div class="max-w-md w-full space-y-8">
        <form class="mt-8 space-y-6" method="POST">
            {% csrf_token %}
            <h1 class="text-2xl font-bold text-indigo-700">{{ review.books.title }}</h1>
            <h2 class="text-lg font-semibold text-gray-800">{{ review.books.author }}</h2>
            <div>
                <label class="block text-gray-700 text-sm font-bold mb-2" for="ratings">
                    Ratings
                </label>
                {{ form.ratings }} 
            </div>
            <div>
                <label class="block text-gray-700 text-sm font-bold mb-2" for="comments">
                    Comments
                </label>
                {{form.comments}}
            </div>
            <div>
                <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
                    {% trans 'Update'%}
                </button>
            </div>
        </form>
    </div>
</div>
{% endblock %}