src/accounts/urls.py
from django.urls import path

from src.accounts.views import auth_views, profile_views

app_name = 'accounts'

urlpatterns = [
    path('login/', auth_views.Login.as_view(), name='login'),
    path('register/', auth_views.RegisterView.as_view(), name='register'),
    path('logout/', auth_views.Logout.as_view(), name='logout'),
    path(
        'profile/',
        profile_views.SelfProfileView.as_view(),
        name='self-profile'
    ),
    path(
        'profile/update/',
        profile_views.ProfileUpdateView.as_view(),
        name='profile-update'
    ),
    path(
        'profile/<str:username>',
        profile_views.ProfileView.as_view(),
        name='profile'
    ),
    path(
        'address/add/',
        profile_views.AddressCreateView.as_view(),
        name='address-create'
    ),
    path(
        'addresses/',
        profile_views.AddressListView.as_view(),
        name='address-list'
    ),
    path(
        'address/<int:pk>/update/',
        profile_views.AddressUpdateView.as_view(),
        name='address-update'
    ),
]

src/root/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.UserHomeView.as_view(), name='home'),
    path('set-language/', views.set_language, name='set_language'),
]

src/shopping/urls.py
from django.urls import path

from .views import cart_views, order_views, payment_views

app_name = 'shopping'

urlpatterns = [
    path('cart/add/', cart_views.AddToCartView.as_view(), name='add_to_cart'),
    path(
        'cart/remove/',
        cart_views.RemoveFromCartView.as_view(),
        name='remove_from_cart'
    ),
    path(
        'cart/delete/',
        cart_views.DeleteFromCartView.as_view(),
        name='delete_from_cart'
    ),
    path('cart/', cart_views.cart_detail, name='cart-detail'),
    path(
        'orders/',
        order_views.OrderHistoryView.as_view(),
        name='order-history'
    ),
    path(
        'order/<int:pk>/',
        order_views.OrderDetailView.as_view(),
        name='order-detail'
    ),
    path('checkout/', order_views.PlaceOrderView.as_view(), name='checkout'),
    path(
        'payment/<int:pk>/',
        payment_views.PaymentView.as_view(),
        name='payment'
    ),
    path(
        'payment/<int:pk>/success/',
        payment_views.PaymentSuccess.as_view(),
        name='payment_success'
    ),
    path(
        'payment/<int:pk>/fail/',
        payment_views.PaymentFail.as_view(),
        name='payment_fail'
    ),
    path(
        'payment/<int:pk>/cancel/',
        payment_views.payment_cancel,
        name='payment_cancel'
    ),
    path('payment/<int:pk>/ipn/', payment_views.ipn, name='ipn'),
]

src/core/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class SoftDeletionManager(models.Manager):

    def get_queryset(self):
        return super().get_queryset().filter(deleted=False)


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True,
                                      verbose_name=_('created_at'))
    updated_at = models.DateTimeField(auto_now=True,
                                      verbose_name=_('deleted_at'))
    deleted = models.BooleanField(default=False,
                                  verbose_name=_('deleted'))

    objects = SoftDeletionManager()
    all_objects = models.Manager(
    )  # Manager to access all objects, including soft-deleted ones

    def delete(self, using=None, keep_parents=False):
        self.deleted = True
        self.save()

    def hard_delete(self):
        super().delete()

    class Meta:
        abstract = True

src/core/templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Welcome {% endblock %} | Paperbound Pavilion</title>

    {% load static %}
    {% load i18n %}
    <script src="https://kit.fontawesome.com/325f18a2d3.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
    {% block extra_scripts %}{% endblock extra_scripts %}
    <link rel="stylesheet" href="{% static "css/output.css" %}">
</head>
<body>
    {% block navbar %}{% endblock navbar %}
    <div class="p-4">
        {% block content %}{% endblock content %}
    </div>
</body>
</html>

src/core/templates/_form.html
<form class="p-4" method="POST" action="{{ action_url }}">
    {% csrf_token %}
    {% for field in form %}
    <div class="mb-4">
        <label class="block text-gray-700 text-sm font-bold mb-2" for="{{ field.id_for_label }}">
            {{ field.label }}
        </label>
        {% if field.field.widget.input_type == 'text' or field.field.widget.input_type == 'number' %}
            <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" type="{{ field.field.widget.input_type }}" name="{{ field.name }}" id="{{ field.id_for_label }}" value="{{ field.value|default_if_none:'' }}">
        {% elif field.field.widget.input_type == 'select' %}
            {% if field.field.choices %}
            <select class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="{{ field.name }}" id="{{ field.id_for_label }}" {% if field.field.widget.allow_multiple_selected %} multiple {% endif %}>
                {% for choice in field.field.choices %}
                    <option value="{{ choice.0 }}" {% if choice.0 in field.value %} selected {% endif %}>{{ choice.1 }}</option>
                {% endfor %}
            </select>
            {% endif %}
        {% else %}
            <textarea class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" name="{{ field.name }}" id="{{ field.id_for_label }}">{{ field.value|default_if_none:'' }}</textarea>
        {% endif %}
        {% if field.errors %}
            <p class="text-red-500 text-xs italic mt-1">{{ field.errors|join:", " }}</p>
        {% endif %}
    </div>
    {% endfor %}
    <div class="flex items-center justify-between">
        <button class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline" type="submit">
            {{ submit_text }}
        </button>
    </div>
</form>

src/core/templates/base.html
{% extends "_base.html" %}

{% block navbar %}
{% load i18n %}
  <!-- navbar.html -->
<nav class="bg-gray-800 shadow-lg">
    <div class="max-w-7xl mx-auto px-2 sm:px-6 lg:px-8">
      <div class="relative flex items-center justify-between h-16">
        <!-- Website name -->
        <div class="flex-shrink-0 flex items-center">
          <a href="/" class="text-white text-2xl font-bold">Paperbound Pavilion</a>
        </div>
        <!-- Nav links -->
        <div class="flex items-center">
          <a href="{% url 'book-list' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">{% trans "Books" %}</a>
          {% if request.user.is_authenticated %}
          <a href="{% url 'shopping:order-history' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">{% trans "OrderHistory" %}</a>
          {% endif %}
          <a href="{% url 'book-search' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">{% trans "FindBooks" %}</a>
        </div>
        <!-- Search bar -->
        <form method="GET" action='{% url "book-search" %}'>
          <div class="flex-1 flex justify-center px-2 lg:ml-6 lg:justify-end">
            <div class="max-w-lg w-full lg:max-w-xs">
              <label for="search" class="sr-only">{% trans "Search" %}</label>
              <div class="relative">
                <div class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                  <!-- Heroicon name: search -->
                  <svg class="h-5 w-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                    <path fill-rule="evenodd" d="M15.854 14.146a1 1 0 0 1-1.415 1.415l-3.792-3.792a6 6 0 1 1 1.415-1.415l3.792 3.792zM14 8a6 6 0 1 0-12 0 6 6 0 0 0 12 0z" clip-rule="evenodd" />
                  </svg>
                </div>
                  <input type="text" name="search_type" value="general" hidden>
                  <input id="search" name="query" class="block w-full pl-10 pr-3 py-2 border border-gray-300 rounded-md leading-5 bg-white placeholder-gray-500 focus:outline-none focus:placeholder-gray-400 focus:border-blue-300 focus:ring focus:ring-blue-200 focus:ring-opacity-50 sm:text-sm" placeholder="Search" type="search">
                </div>
              </div>
              <input type="submit" value="Search" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text">
            </div>
        </form>

        <!-- Nav links -->
        <div class="flex items-center">
          <a href="{% url 'shopping:cart-detail' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"><i class="fa-solid fa-cart-shopping"></i></a>
          {% comment %} <a href="{% url 'book-search' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">{% trans "FindBooks" %}</a> {% endcomment %}
        </div>

        <!-- LANGS -->
        {% get_current_language as CURRENT_LANGUAGE %}
        {% get_available_languages as AVAILABLE_LANGUAGES %}
        {% get_language_info_list for AVAILABLE_LANGUAGES as languages %}
        <div class="languages">
          <ul class="languages flex">
            <form id="language-form" method="GET" action="{% url 'set_language' %}">
              {% csrf_token %}
              {% for language in AVAILABLE_LANGUAGES %}
                
                  <button type="submit" name="language" value="{{ language.0 }}" 
                  class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">
                    {{ language.1 }}
                  </button>
                
              {% endfor %}
          </form>
          </ul>
        </div>

        <!-- LOGOUT -->
        {% if request.user.is_authenticated %}
          <div class="flex items-center">
            <form action="{% url 'accounts:logout' %}" method="POST">
              {% csrf_token %}
              <button type="submit" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium">{% trans "Log out" %}</a>
            </form>
          </div>
          <a href="{% url 'accounts:self-profile' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"><i class="fa-solid fa-user"></i></a>
        {% else %}
          <div class="flex items-center">
            <a href="{% url 'accounts:login' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text">{% trans "LogIn" %}</a>
            <a href="{% url 'accounts:register' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text">{% trans "Register" %}</a>
          </div>
        {% endif %}
        
      </div>
    </div>
  </nav>
  
{% endblock navbar %}

src/core/templates/delete-confirmation.html
{% extends 'store_admin/admin_base.html' %}
{% load i18n %}

{% block title %}
  {{ title }}
{% endblock %}
{% block header %}
  {{ header }}
{% endblock %}

{% block content %}
  <div class="bg-white p-8 rounded-md shadow-md m-8">
    <h1 class="text-2xl font-bold mb-4 text-center">{{ title }}</h1>
    <p class="text-center mb-6">Are you sure you want to delete {{ model }} '{{ object }}'?</p>
    <form method="post">
      {% csrf_token %}
      <div class="flex justify-center">
        <button type="submit" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-md">Confirm</button>
      </div>
    </form>
  </div>
{% endblock %}

src/core/templates/form.html
<div class="container mx-auto p-4">
    <h2 class="text-3xl font-semibold mb-4">{{ form_title }}</h2>
    <div class="bg-gray-100 rounded-lg shadow-md overflow-hidden">
        {% include "_form.html" %}
    </div>
</div>